export interface Transaction {
  id: string;
  date: string;
  merchant: string;
  category: string;
  subcategory: string;
  subsubcategory: string;
  categoryPath: string[];
  account: string;
  amount: number;
  type: "expense" | "income";
}

// These are now computed dynamically from generated data — see DataContext
// Kept as re-exports for backward compatibility
export const allCategories: string[] = [];
export const allAccounts: string[] = [];

// Legacy static data removed — all data is now generated by syntheticEngine
export const demoTransactions: Transaction[] = [];
